mod animal;
mod animu;
mod canvas;
mod chatbot;
mod fact;
mod image;
mod others;
mod pokemon;
mod premium;
mod welcome;

pub use animal::*;
pub use animu::*;
pub use canvas::*;
pub use chatbot::*;
pub use fact::*;
pub use image::*;
pub use others::*;
pub use pokemon::*;
pub use premium::*;
pub use welcome::*;
